import { useState } from 'react';
import { useGameStore, isCheckpointFloor } from '../../game/store/gameStore';
import { useUIStore } from '../../game/store/uiStore';
import { playSfx } from '../../utils/audio';
import { Button } from '../ui/Button';
import { Panel } from '../ui/Panel';
import { SoundToggle } from '../ui/SoundToggle';

/** Inn price: 15g x level, escalating per consecutive rest without descending. */
export function getInnCost(level: number, restsThisVisit: number): number {
  return 15 * level * (restsThisVisit + 1);
}

export function TownScreen() {
  const player = useGameStore((s) => s.player);
  const dungeon = useGameStore((s) => s.dungeon);
  const setScreen = useGameStore((s) => s.setScreen);
  const setDungeon = useGameStore((s) => s.setDungeon);
  const setSelectedShop = useGameStore((s) => s.setSelectedShop);
  const setStatsReturn = useGameStore((s) => s.setStatsReturn);
  const save = useGameStore((s) => s.save);
  const updatePlayer = useGameStore((s) => s.updatePlayer);
  const lastSave = useGameStore((s) => s.lastSave);
  const stats = useGameStore((s) => s.stats);
  const dailyKey = useGameStore((s) => s.dailyKey);
  const addLog = useUIStore((s) => s.addLog);

  const [restsThisVisit, setRestsThisVisit] = useState(0);

  if (!player) return null;

  const innCost = getInnCost(player.level, restsThisVisit);

  const handleRest = () => {
    const cost = getInnCost(player.level, restsThisVisit);
    if (player.gold < cost) {
      addLog(`Inn costs ${cost}g — you have ${player.gold}g. Clear rooms for gold first.`, 'danger');
      return;
    }
    const newStats = { ...player.stats, hp: player.stats.maxHp, mp: player.stats.maxMp };
    playSfx('rest');
    updatePlayer({ stats: newStats, gold: player.gold - cost });
    setRestsThisVisit((n) => n + 1);
    save();
    const next = getInnCost(player.level, restsThisVisit + 1);
    addLog(`Rested at the Inn (-${cost}g). HP/MP restored. Game saved. Next rest: ${next}g.`, 'system');
  };

  const handleEnterDungeon = () => {
    // Resume the cached run map whenever one exists — never reroll a fresh
    // floor over cleared rooms. Fresh floors are only generated by descending.
    const existing = useGameStore.getState().dungeon;
    if (existing) {
      if (existing.floor === player.floor) {
        addLog(`Resuming dungeon floor ${player.floor}...`, 'system');
      } else {
        addLog(`Resuming saved floor ${existing.floor} (you left at ${player.floor})...`, 'system');
        // Legacy saves can disagree — the map is authoritative so descending
        // continues from the floor you're actually standing on.
        updatePlayer({ floor: existing.floor });
      }
      setRestsThisVisit(0);
      setScreen('dungeon');
      return;
    }
    addLog(`Entering dungeon floor ${player.floor}...`, 'system');
    setRestsThisVisit(0);
    setDungeon(null);
    setScreen('dungeon');
  };

  const goStats = (from: 'town') => {
    setStatsReturn(from);
    setScreen('stats');
  };

  const goShop = (shop: 'blacksmith' | 'potion_shop' | 'magic_shop') => {
    setSelectedShop(shop, 'town');
    setScreen('shop');
  };

  const points = player.statPoints ?? 0;
  const checkpoint = isCheckpointFloor(player.floor);

  return (
    <div className="flex flex-col min-h-[70vh] justify-center gap-5 animate-fade-in max-w-md mx-auto">
      <div className="text-center">
        <div className="text-terminal-green text-xs tracking-widest">[ TOWN OF HAVEN ]</div>
        <div className="text-terminal-dim text-[11px] mt-1">Rest, resupply, then descend.</div>
      </div>

      <Button variant="danger" onClick={handleEnterDungeon} glow className="w-full">
        {dungeon && dungeon.floor === player.floor ? 'Resume Dungeon' : 'Enter Dungeon'}
      </Button>

      {dailyKey && (
        <div className="text-center text-[11px] text-terminal-yellow border border-terminal-yellow/40 px-2 py-1">
          DAILY CHALLENGE — {dailyKey} · one seed, one leaderboard
        </div>
      )}

      <div className="grid grid-cols-2 gap-2 w-full">
        <Button onClick={handleRest}>Inn ({innCost}g)</Button>
        <Button onClick={() => goStats('town')}>
          {points > 0 ? `Stats (${points})` : 'Stats'}
        </Button>
        <Button onClick={() => setScreen('questBoard')}>Quests</Button>
        <Button onClick={() => setScreen('inventory')}>Inventory</Button>
        <Button onClick={() => setScreen('meta')}>Renown</Button>
        <Button onClick={() => setScreen('bestiary')}>Bestiary</Button>
      </div>

      <Panel title="Shops — resupply here" titleAlign="center">
        <div className="flex flex-col gap-2">
          <Button size="sm" variant="ghost" className="w-full" onClick={() => goShop('blacksmith')}>
            Blacksmith <span className="text-terminal-dim normal-case">— weapons & armor</span>
          </Button>
          <Button size="sm" variant="ghost" className="w-full" onClick={() => goShop('potion_shop')}>
            Potion Shop <span className="text-terminal-dim normal-case">— HP & MP</span>
          </Button>
          <Button size="sm" variant="ghost" className="w-full" onClick={() => goShop('magic_shop')}>
            Magic Shop <span className="text-terminal-dim normal-case">— charms & spells</span>
          </Button>
        </div>
      </Panel>

      <div className="text-center text-[11px] text-terminal-dim">
        Floor {player.floor} · Best {Math.max(stats.bestFloor, player.floor)} · Bosses {stats.bossesKilled}
        {!checkpoint && <span> · checkpoint at floor {Math.ceil(player.floor / 5) * 5}</span>}
        {lastSave && <span> · saved {new Date(lastSave).toLocaleTimeString()}</span>}
      </div>
      <div className="flex justify-center">
        <SoundToggle />
      </div>
    </div>
  );
}
